var form = document.getElementById("my-form");
    
    async function handleSubmit(event) {
      //event.preventDefault();
      var status = document.getElementById("my-form-status");
      var data = new FormData(event.target);
      fetch(event.target.action, {
        method: form.method,
        body: data,
        headers: {
            'Accept': 'application/json'
        }
      }).then(response => {
        if (response.ok) {
          status.innerHTML = "Thanks for your submission!";
          form.reset()
        } else {
          response.json().then(data => {
            if (Object.hasOwn(data, 'errors')) {
              status.innerHTML = data["errors"].map(error => error["message"]).join(", ")
            } else {
              status.innerHTML = "Oops! There was a problem submitting your form"
            }
          })
        }
      }).catch(error => {
        status.innerHTML = "Oops! There was a problem submitting your form"
      });
    }
    form.addEventListener("submit", handleSubmit)

function darkMode(){


    document.getElementByID("darkMode").style.backgroundColor = "red"; 
    window.setTimeout("yourFunction()",10000);
}



function getRandomQuote() {
    //declare an array to store the images  
    var randomPhrase = new Array();
    //insert the URL of images in array  
    randomPhrase[0] = "“We cannot solve problems with the kind of thinking we employed when we came up with them.” — Albert Einstein";
    randomPhrase[1] = "“Try not to become a man of success, but rather become a man of value.”   Albert Einstein"
    randomPhrase[2] = "“True freedom is impossible without a mind made free by discipline.” ―Mortimer J. Adler";
    randomPhrase[3] = "“If you can't yet do great things, do small things in a great way.” ―Napoleon Hill";
    randomPhrase[4] = "“If you really want to do something, you'll find a way. If you don't, you'll find an excuse.” ―Jim Rohn";
    randomPhrase[5] = "“Live out of your imagination, not your history.” —Stephen Covey";
    randomPhrase[6] = "“I have not failed. I've just found 10,000 ways that won't work.” — Thomas A. Edison";
    randomPhrase[7] = "“We can see through others only when we can see through ourselves.” – Bruce Lee";
    randomPhrase[8] = "“More is lost by indecision than wrong decision.” —Marcus Tullius Cicero";
    //generate a number and provide to the image to generate randomly  
    var number = Math.floor(Math.random() * randomPhrase.length);
    //return the images generated by a random number  
    return document.getElementById("quote").innerHTML = randomPhrase[number];
}
